name: Build KMM Librari

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build KMM Library
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # - name: Build Android Library
    #   run: ./gradlew :shared:assembleDebug
    
    # - name: Build iOS Library
    #   run: ./gradlew :shared:linkDebugFrameworkIosX64

    - name: Build ALL
      run: ./gradlew :shared:build